encoding: utf-8

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Alexander Parker'
tagline:          'Alexander Parker'
description:      'Data Science & Programming'
url:              https://alexander-parker.github.io/

author:
  name:           'Alexander Parker'
  url:            https://alexander-parker.github.io/

paginate:         25
future:           true

github:
  repo:           https://github.com/Alexander-Parker/Alexander-Parker.github.io

gems:
  - jekyll-sitemap
  
picture:
  source: "public/img/_original"
  output: "public/img"
  markup: "picturefill"
  presets:
    default:
      ppi: [1]
      attr:
        class: "default-img"
        itemprop: "image"
      source_large:
        media: "(min-width: 35em)"
        width: "720"
      source_medium:
        media: "(min-width: 25em)"
        width: "400"
      source_small:
        media: "(min-width: 12.5em)"
        width: "200"
      source_default:
        width: "1000"
