# Permalinks
permalink:           pretty

# Setup
title:               Alexander Parker
tagline:             Yet Another Github Blog
url:                 https://alexander-parker.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alexander Parker
  url:               https://github.com/Alexander-Parker
  email:             alexanderparker@utexas.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Alexander-Parker/Alexander-Parker.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
